### ISSUE TITLE
CLIP ViT-S/16 model weights

### ISSUE THREAD

**Issue by vishaal27** [UCSC-VLAA/CLIPA#1]
Hi,
I have a slightly unusual request, but one that I hope you that might accede---I am studying scaling laws for CLIP-like models and would like to have access to the baseline CLIP ViT-S/16 models that you trained (I think you have only released CLIPA weights for ViT-B/16 onwards). I am especially interested in the unoptimised base CLIP ViT-S/16 models (i.e. the one that always uses full image resolution and maximum text token length). So far, I was unable to find any open-source pre-trained CLIP model weights (OpenAI/OpenCLIP/DataComp/CyCLIP/FLIP) that use image ViT encoders smaller than ViT-B. I also did a brief search on HuggingFace but to no avail. I would also be grateful if you could point me to any pre-trained CLIP weights where the image encoder used is a ViT but smaller than ViT-B.

**Comment by xhl-video** [comment]
Hello,
Thank you for your inquiry and interest in obtaining the baseline CLIP ViT-S/16 models. We are pleased to provide you with the JAX version checkpoints and logs, which you can access by following this link: [S/16 model checkpoints](https://drive.google.com/drive/folders/1RRs_u7xcyFCC9lAIMLOV5sPE-g2tKgNy?usp=drive_link). Within the folder, you will find the top three S/16 models that correspond to the S/16 variant mentioned in Figure 4 of our paper. We hope that these resources are helpful to you.
