### ISSUE TITLE
Training is too slow

### ISSUE THREAD

**Issue by eslambakr** [UCSC-VLAA/CLIPA#10]
Thanks for sharing your great work!

I have started the training on 1 A100 just to test the environment and everything, and it works fine but as shown in the below image the estimated time is too much.
After I made the simple calculation based on this information this means training only one epoch using 8 A100 will take 10 days which of course does not make any sense!

So from your experience what may cause this issue? I am using `webdataset` not `tfrecord` but I am not sure this could cause this degradation or not.
Also if this is the issue can you advice how may I convert it to tfrecord format?

Thanks in advance!

<img width="1290" alt="image" src="https://github.com/UCSC-VLAA/CLIPA/assets/25908688/df4c4aad-e651-4f83-b3e6-e001f316d617">

**Comment by zw615** [comment]
Hi I wonder what is the detailed training config (e.g. model, total training samples, image/text token length, etc)? In our experience, training a large model does take a lot of time. For instance, the training of a ViT-L model for about 2.4B samples took us about three days on a 8-A100 machine (even with reduced token length!). So if you are trying a larger model or a longer schedule, it might be reasonable to see a longer training time.

**Comment by eslambakr** [comment]
Thanks for your response!

The issue was the number of CPUs. Once I increase them the GPU becomes fully utilized and the training time dropped significantly.
