### ISSUE TITLE
How about releasing the weights of models with small input size

### ISSUE THREAD

**Issue by OblivionStaff** [UCSC-VLAA/CLIPA#2]
Hi,

Thanks for your great work. In some resource limited scenario, it will benefit to use the model with smaller input size.  And the performance drop is acceptable. Would you consider to release the model weights before fine-tuning with the full input size?

Thanks.

**Comment by xhl-video** [comment]
Hi,

Thank you for your interest in our work. We are pleased to provide you with the pre-trained weights for CLIPA-V2. You can access them on [Google Drive](https://drive.google.com/drive/folders/1ArW1-JL7DL43ifg47cIJ4CBeMFIpPkrR?usp=sharing). The performance metrics are detailed in the clipa_jax/README.MD file. Additionally, we have included the configurations and logs in the shared weights directory. We hope you find this information helpful!
