### ISSUE TITLE
How to download gs://vit_models/lit/bert/uncased_L-12_H-768_A-12/vocab.txt?

### ISSUE THREAD

**Issue by YehLi** [UCSC-VLAA/CLIPA#3]
Thanks for the great work. How to download gs://vit_models/lit/bert/uncased_L-12_H-768_A-12/vocab.txt? Can the text encoder due with long sentence (e.g., sentence with 77 tokens? )

**Comment by xhl-video** [comment]
Thank you for your interest in our work. We have included the vocab.txt file in the repo, which can be found in this [folder](https://github.com/UCSC-VLAA/CLIPA/blob/master/data/vocab.txt). By default, we followed FLIP for fine-tuning with a length of 32. However, we did not observe significant improvements when tuning with longer sentences on LAION dataset. Nevertheless, it is possible to fine-tune a text encoder with 77 tokens as input.

**Comment by YehLi** [comment]
Thanks for your quick reply. Can the text encoder encode long sentence without fine-tuning? I want to replace the [CLIP ViT-L/14] with CLIPA. However, I am not sure whether the CLIPA can adapt to long tokens as [CLIP ViT-L/14].

**Comment by xhl-video** [comment]
If you would like to utilize CLIPA's text encoder, I recommend fine-tuning it for encoding longer sentences. Alternatively, you can also consider partially fine-tuning specific layers, such as the position embedding layer. On the other hand, if your intention is to only use CLIPA's visual encoder, it is possible to incorporate another text encoder without the need for fully fine-tuning. However,  I have not tried this before.
